export interface Account {
    uid?: string,
    email: string,
    phone?: string,
    type?: string,
    name: string,
    surname: string,
    social_name?: string,
    gender?: string,
}

export interface Specialist extends Account{
	phone: string,
	connection: string,
    gender: string,
    specialty: string,
    password?: string,
    confirm_password?: string,
    type?: 'specialist',
}

export interface User extends Account{
	race?: string,
    schooling?: string,
    individual_income?: string,
    family_income?: string,
    address?: string,
    birthday?: Date,
    password?: string,
    confirm_password?: string,
    type?: 'user',
    specialistId?: string,
}

export interface PageUser{
    id: string,
    name: string,
    race: string,
    schooling: string,
    individual_income: string,
    family_income: string,
    address: string,
    city: string,
    state: string,
    birthday: Date,
    age: number,
    phone: string,
    gender: string,
    sex: string,
    status: string,
    schooling_years: number,
    retirement: string,
    career: string,
    job: string,
    job_name: string,
    religion: string,
    religion_name: string,
    selfreport: string,
    housemates: string,
    housemates_name: string,
    type?: 'page_user',
    specialistId?: string,
}