import '@/styles/globals.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Toaster } from "@/components/ui/toaster";
import SessionProvider from "@/components/provider/SessionProvider";
import ChakraUIProvider from "@/components/provider/ChakraUIProvider";
import NextuiProvider from "@/components/provider/NextUIProvider";
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={cn("flex", inter.className)}>
                <SessionProvider>
                    <Sidebar/>
                    <main className="flex flex-col justify-center items-center min-h-screen w-full">
                        {children}
                    </main>
                    <Toaster/>
                </SessionProvider>
            </body>
        </html>
    );
}
