import '@/styles/globals.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Toaster } from "@/components/ui/toaster";
import SessionProvider from "@/components/provider/SessionProvider";
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <SessionProvider>
                <body className={cn("flex flex-1 w-full min-h-full h-fit bg-background", inter.className)}>
                    <Sidebar/>
                    <main className="flex flex-1 flex-col justify-center items-center pl-sidebar py-16">
                        {children}
                    </main>
                    <Toaster/>
                </body>
            </SessionProvider>
        </html>
    );
}
